name: Run Jupyter Notebook

on:
  schedule:
    # Runs at 7:00 AM every day
    - cron: '36 10 * * *'

jobs:
  run-notebook:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install notebook
        pip install nbconvert
        pip install jupyter

    - name: Run Jupyter Notebook
      run: |
        jupyter nbconvert --to notebook --execute ump-indonesia-2022-2023.ipynb
